---
title: "HospitalData"
author: "ditiatev"
date: "16 05 2020"
output: html_document
---
## Load librares

```{r load-packages, message = FALSE}
library(ggplot2)
library(dplyr)
library(statsr)
library(GGally)
```

## Data

```{r}
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
```

```{r}
names(outcome)
```

```{r}
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11])
```

function read file "outcome-of-care-measures.csv" and get best clinic for outcome:

- "heart attack"
- "heart failure"
- "pneumonia"

```{r}
best <- function(state, outcome) {
    ## Read outcome data
    data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
    
    ## Check that state and outcome are valid
    if (!(state %in% unique(data$State))) stop(" invalid state")
    if (!(outcome %in% c("heart attack", "heart failure", "pneumonia"))) stop(" invalid  outcome")
    
    ## Return hospital name in that state with lowest 30-day death
    colnum <- function(outcome) {
        n <- if (outcome == "heart attack") {
            11
        } else if (outcome == "heart failure") {
            17
        } else {
            23
        }
        n
    }
    
    n <- colnum(outcome)
    data <- data[which(data$State == state & data[,n] != "Not Available"),]
    data[,n] <- as.numeric(data[,n])
    data <- data[order(data[,n], data[,2]),]
    ## rate
    data[[1,2]]
}
```

```{r}
best("MD", "heart attack")
```

```{r}
debug(best)
#undebug(best)
```

```{r}
rankhospital <- function(state, outcome, num = "best") {
    ## Read outcome data
    data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
    
    ## Check that state and outcome are valid
    if (!(state %in% unique(data$State))) stop(" invalid state")
    if (!(outcome %in% c("heart attack", "heart failure", "pneumonia"))) stop(" invalid  outcome")
    
    ## Return hospital name in that state with lowest 30-day death
    colnum <- function(outcome) {
        n <- if (outcome == "heart attack") {
            11
        } else if (outcome == "heart failure") {
            17
        } else {
            23
        }
        n
    }
    
    n <- colnum(outcome)
    data <- data[which(data$State == state & data[,n] != "Not Available"),]
    data[,n] <- as.numeric(data[,n])
    data <- data[order(data[,n],data[,2]),]
    
    ## rate
    if (num == "best") {
        num <- 1
    } else if (num == "worst") {
        num <- nrow(data)
    } else if (num > nrow(data)) {
        return(NA)
    }
    
    data[[num,2]]
}
```

```{r}
rankhospital("MD", "heart attack", num = 5000)
```

```{r}
rankall <- function(outcome, num = "best") {
    ## Read outcome data
    data <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
    
    ## Check outcome are valid
    if (!(outcome %in% c("heart attack", "heart failure", "pneumonia"))) stop(" invalid  outcome")
    
    ## Return hospital name in that state with lowest 30-day death
    colnum <- function(outcome) {
        n <- if (outcome == "heart attack") {
            11
        } else if (outcome == "heart failure") {
            17
        } else {
            23
        }
        n
    }
    
    n <- colnum(outcome)
    data <- data[which(data[,n] != "Not Available"),]
    data[,n] <- as.numeric(data[,n])
    data <- data[order(data$State,data[,n],data[,2]),]
    
    ## rate
    rate <- function(x, num)
    if (num == "best") {
        x[1]
        #data[[1,2]]
    } else if (num == "worst") {
        #data[[nrow(data),2]]
        x[length(x)]
    } else if (num > length(x)) {
        NaN
    } else {
        x[num]
    }
   # FUN=function(x2) getpos(x2, vorl="l")
    df1 <- tapply(data[,2], data$State, FUN = function(x) rate(x, num))
    df2 <- tapply(data[,n], data$State, FUN = function(x) rate(x, num))
    df3 <- tapply(data[,7], data$State, FUN = function(x) rate(x, num))
    df <- cbind.data.frame(hospital = df1, rank = df2, state = df3)
    df
}
```

```{r}
df <- rankall("heart attack", num = 3)
df
```
```{r}
r <- rankall("heart failure", 10)
as.character(subset(r, state == "NV")$hospital)
```


