---
title: "Text"
author: "ditiatev"
date: "31 05 2020"
output: html_document
---

```{r}
if (!file.exists("data")) {dir.create("data")}
FileUrl <- "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.csv?accessType=DOWNLOAD"
download.file(FileUrl, destfile = "./data/camera.csv")
cameraData <- read.csv("./data/camera.csv")
names(cameraData)
```

### LowerCase

```{r}
tolower(names(cameraData))
```

### Split

```{r}
splitNames <- strsplit(names(cameraData),"\\.")
```

```{r}
splitNames[[7]]
```




```{r}
if(!file.exists("./data")) {dir.create("./data")}
fileUrl1 <- "https://raw.githubusercontent.com/jtleek/dataanalysis/master/week2/007summarizingData/data/reviews.csv"
fileUrl2 <- "https://raw.githubusercontent.com/jtleek/dataanalysis/master/week2/007summarizingData/data/solutions.csv"
download.file(fileUrl1, destfile = "./data/reviews.csv")
download.file(fileUrl2, destfile = "./data/solution.csv")
reviews <- read.csv("./data/reviews.csv")
solution <- read.csv("./data/solution.csv")
```

```{r}
head(reviews,2)
```

```{r}
head(solution,2)
```


# Replacing character
## sub() 
- replaced one (first) character on another

```{r}
names(reviews)
```

```{r}
sub("_","",names(reviews))
```

## gsub()
- replaced one (all) character on another

```{r}
testName <- "this_is_a_test"
sub("_","",testName)
```

```{r}
gsub("_","",testName)
```




























