---
title: "week2quiz"
author: "ditiatev"
date: "21 05 2020"
output: html_document
---

```{r}
#install.packages("sqldf")
library(sqldf)
library(RMySQL)
```

```{r}
getwd()
setwd("C:/R/0_courses/JHU_DataScience/GettingCleaningData/Week2")
```

```{r}
if (!file.exists("data")) {
    dir.create("data")
}
```

```{r}
FileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv"
download.file(FileUrl, destfile = "./data/acs.csv")
list.files("./data")
```
```{r}
acs <- read.csv("./data/acs.csv")
```

```{r}
head(acs)
```


```{r}
sqldf("select distinct AGEP from acs where AGEP < 50")
```

```{r}
View(sqldf("select distinct AGEP from acs"))
```



```{r}
library(XML)
FileUrl <- "http://biostat.jhsph.edu/~jleek/contact.html"
doc <- xmlTreeParse(FileUrl, 
                    useInternalNodes = TRUE
                    )
rootNote <- xmlRoot(doc)
xmlName(rootNote)
```

```{r}
library(httr)
library(XML)
Url <- "http://biostat.jhsph.edu/~jleek/contact.html"
html2 <- GET(Url)
content2 <- content(html2,as = "text")
ParserHtml <- htmlParse(content2, asText = T)
xpathSApply(ParserHtml, "//title", xmlValue)
```

```{r}
Url <- "http://biostat.jhsph.edu/~jleek/contact.html"
htmlCode <- readLines(Url)
```


```{r}
c(nchar(htmlCode[10]), nchar(htmlCode[20]), nchar(htmlCode[30]), nchar(htmlCode[100]))
```



